"""adding rows to table for authentication

Revision ID: b4eafe0082d2
Revises: a689e2e520ee
Create Date: 2024-07-06 11:15:27.793611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4eafe0082d2'
down_revision: Union[str, None] = 'a689e2e520ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('full_name', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_column('user', 'password')
    op.drop_column('user', 'login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'disabled')
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
